config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "encounters#index"
  
  # Routes for the admin
  get("/adminpanel", {:controller => "admin_panel", :action => "index"})
  
  # Routes for the summary views
  get("/summary", {:controller => "summary", :action => "show"})
  
  # Routes for the Sex resource:

  # CREATE
  get("/sexes/new", { :controller => "sexes", :action => "new_form" })
  post("/create_sex", { :controller => "sexes", :action => "create_row" })

  # READ
  get("/sexes", { :controller => "sexes", :action => "index" })
  get("/sexes/:id_to_display", { :controller => "sexes", :action => "show" })

  # UPDATE
  get("/sexes/:prefill_with_id/edit", { :controller => "sexes", :action => "edit_form" })
  post("/update_sex/:id_to_modify", { :controller => "sexes", :action => "update_row" })

  # DELETE
  get("/delete_sex/:id_to_remove", { :controller => "sexes", :action => "destroy_row" })

  #------------------------------

  # Routes for the Prescription resource:

  # CREATE
  get("/prescriptions/new", { :controller => "prescriptions", :action => "new_form" })
  post("/create_prescription", { :controller => "prescriptions", :action => "create_row" })
  post("/create_prescription_from_medication", { :controller => "prescriptions", :action => "create_row_from_medication" })
  post("/create_prescription_from_encounter", { :controller => "prescriptions", :action => "create_row_from_encounter" })
  post("/create_prescription_from_patient", { :controller => "prescriptions", :action => "create_row_from_patient" })
  post("/create_prescription_from_prescription", { :controller => "prescriptions", :action => "create_row_from_prescription" })

  # READ
  get("/prescriptions", { :controller => "prescriptions", :action => "index" })
  get("/prescriptions/:id_to_display", { :controller => "prescriptions", :action => "show" })

  # UPDATE
  get("/prescriptions/:prefill_with_id/edit", { :controller => "prescriptions", :action => "edit_form" })
  post("/update_prescription/:id_to_modify", { :controller => "prescriptions", :action => "update_row" })

  # DELETE
  get("/delete_prescription/:id_to_remove", { :controller => "prescriptions", :action => "destroy_row" })
  get("/delete_prescription_from_medication/:id_to_remove", { :controller => "prescriptions", :action => "destroy_row_from_medication" })
  get("/delete_prescription_from_encounter/:id_to_remove", { :controller => "prescriptions", :action => "destroy_row_from_encounter" })
  get("/delete_prescription_from_patient/:id_to_remove", { :controller => "prescriptions", :action => "destroy_row_from_patient" })
  get("/delete_prescription_from_provider/:id_to_remove", { :controller => "prescriptions", :action => "destroy_row_from_provider" })

  #------------------------------

  # Routes for the Med type resource:

  # CREATE
  get("/med_types/new", { :controller => "med_types", :action => "new_form" })
  post("/create_med_type", { :controller => "med_types", :action => "create_row" })

  # READ
  get("/med_types", { :controller => "med_types", :action => "index" })
  get("/med_types/:id_to_display", { :controller => "med_types", :action => "show" })

  # UPDATE
  get("/med_types/:prefill_with_id/edit", { :controller => "med_types", :action => "edit_form" })
  post("/update_med_type/:id_to_modify", { :controller => "med_types", :action => "update_row" })

  # DELETE
  get("/delete_med_type/:id_to_remove", { :controller => "med_types", :action => "destroy_row" })

  #------------------------------

  # Routes for the Medication resource:

  # CREATE
  get("/medications/new", { :controller => "medications", :action => "new_form" })
  post("/create_medication", { :controller => "medications", :action => "create_row" })
  post("/create_medication_from_med_type", { :controller => "medications", :action => "create_row_from_med_type" })

  # READ
  get("/medications", { :controller => "medications", :action => "index" })
  get("/medications/:id_to_display", { :controller => "medications", :action => "show" })

  # UPDATE
  get("/medications/:prefill_with_id/edit", { :controller => "medications", :action => "edit_form" })
  post("/update_medication/:id_to_modify", { :controller => "medications", :action => "update_row" })

  # DELETE
  get("/delete_medication/:id_to_remove", { :controller => "medications", :action => "destroy_row" })
  get("/delete_medication_from_med_type/:id_to_remove", { :controller => "medications", :action => "destroy_row_from_med_type" })

  #------------------------------

  # Routes for the Location resource:

  # CREATE
  get("/locations/new", { :controller => "locations", :action => "new_form" })
  post("/create_location", { :controller => "locations", :action => "create_row" })

  # READ
  get("/locations", { :controller => "locations", :action => "index" })
  get("/locations/:id_to_display", { :controller => "locations", :action => "show" })

  # UPDATE
  get("/locations/:prefill_with_id/edit", { :controller => "locations", :action => "edit_form" })
  post("/update_location/:id_to_modify", { :controller => "locations", :action => "update_row" })

  # DELETE
  get("/delete_location/:id_to_remove", { :controller => "locations", :action => "destroy_row" })

  #------------------------------

  # Routes for the Encounter resource:

  # CREATE
  get("/encounters/new", { :controller => "encounters", :action => "new_form" })
  post("/create_encounter", { :controller => "encounters", :action => "create_row" })
  post("/create_encounter_from_location", { :controller => "encounters", :action => "create_row_from_location" })
  post("/create_encounter_from_patient", { :controller => "encounters", :action => "create_row_from_patient" })

  # READ
  get("/encounters", { :controller => "encounters", :action => "index" })
  get("/encounters/:id_to_display", { :controller => "encounters", :action => "show" })

  # UPDATE
  get("/encounters/:prefill_with_id/edit", { :controller => "encounters", :action => "edit_form" })
  post("/update_encounter/:id_to_modify", { :controller => "encounters", :action => "update_row" })

  # DELETE
  get("/delete_encounter/:id_to_remove", { :controller => "encounters", :action => "destroy_row" })
  get("/delete_encounter_from_location/:id_to_remove", { :controller => "encounters", :action => "destroy_row_from_location" })
  get("/delete_encounter_from_patient/:id_to_remove", { :controller => "encounters", :action => "destroy_row_from_patient" })
  get("/delete_encounter_from_approving_provider/:id_to_remove", { :controller => "encounters", :action => "destroy_row_from_approving_provider" })
  get("/delete_encounter_from_provider/:id_to_remove", { :controller => "encounters", :action => "destroy_row_from_provider" })

  #------------------------------

  # Routes for the Provider credential resource:

  # CREATE
  get("/provider_credentials/new", { :controller => "provider_credentials", :action => "new_form" })
  post("/create_provider_credential", { :controller => "provider_credentials", :action => "create_row" })
  post("/create_provider_credential_from_credential", { :controller => "provider_credentials", :action => "create_row_from_credential" })

  # READ
  get("/provider_credentials", { :controller => "provider_credentials", :action => "index" })
  get("/provider_credentials/:id_to_display", { :controller => "provider_credentials", :action => "show" })

  # UPDATE
  get("/provider_credentials/:prefill_with_id/edit", { :controller => "provider_credentials", :action => "edit_form" })
  post("/update_provider_credential/:id_to_modify", { :controller => "provider_credentials", :action => "update_row" })

  # DELETE
  get("/delete_provider_credential/:id_to_remove", { :controller => "provider_credentials", :action => "destroy_row" })
  get("/delete_provider_credential_from_credential/:id_to_remove", { :controller => "provider_credentials", :action => "destroy_row_from_credential" })
  get("/delete_provider_credential_from_provider/:id_to_remove", { :controller => "provider_credentials", :action => "destroy_row_from_provider" })

  #------------------------------

  # Routes for the Credential resource:

  # CREATE
  get("/credentials/new", { :controller => "credentials", :action => "new_form" })
  post("/create_credential", { :controller => "credentials", :action => "create_row" })

  # READ
  get("/credentials", { :controller => "credentials", :action => "index" })
  get("/credentials/:id_to_display", { :controller => "credentials", :action => "show" })

  # UPDATE
  get("/credentials/:prefill_with_id/edit", { :controller => "credentials", :action => "edit_form" })
  post("/update_credential/:id_to_modify", { :controller => "credentials", :action => "update_row" })

  # DELETE
  get("/delete_credential/:id_to_remove", { :controller => "credentials", :action => "destroy_row" })

  #------------------------------

  # Routes for the Patient resource:

  # CREATE
  get("/patients/new", { :controller => "patients", :action => "new_form" })
  post("/create_patient", { :controller => "patients", :action => "create_row" })
  post("/create_patient_from_sex", { :controller => "patients", :action => "create_row_from_sex" })

  # READ
  get("/patients", { :controller => "patients", :action => "index" })
  get("/patients/:id_to_display", { :controller => "patients", :action => "show" })

  # UPDATE
  get("/patients/:prefill_with_id/edit", { :controller => "patients", :action => "edit_form" })
  post("/update_patient/:id_to_modify", { :controller => "patients", :action => "update_row" })

  # DELETE
  get("/delete_patient/:id_to_remove", { :controller => "patients", :action => "destroy_row" })
  get("/delete_patient_from_sex/:id_to_remove", { :controller => "patients", :action => "destroy_row_from_sex" })

  #------------------------------

  devise_for :providers
  # Routes for the Provider resource:

  # READ

app/models/provider.rb
class Provider < ApplicationRecord
  # Direct associations

  has_many   :approved_encounters,
             :class_name => "Encounter",
             :foreign_key => "approving_provider_id"

  has_many   :prescriptions

  has_many   :encounters

  has_many   :provider_credentials,
             :dependent => :destroy

  # Indirect associations

  has_many   :credentials,
             :through => :provider_credentials,
             :source => :credential

  def fullname
   "#{firstname} #{lastname}"
  end

  # Validations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/views/provider_templates/_provider_approved_encounters.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Approved Encounters (<%=@provider.approved_encounters.count%> total)
  </div>

  <ul class="list-group list-group-flush">
    <% @provider.approved_encounters.each do |encounter| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/encounters/<%= encounter.id %>">
          <%= encounter.provider.firstname %> <%= encounter.provider.lastname %> seeing <%= encounter.patient.firstname %> <%= encounter.patient.lastname %> on <%= encounter.created_at.to_date %> @ <%= encounter.location.name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/provider_templates/_provider_credentials.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Credentials

    <a data-toggle="collapse" href="#provider_credentials_new_form">
      Add credential
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @provider.credentials.each do |credential| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/credentials/<%= credential.id %>">
          <%= credential.name %>
        </a>

      </li>
    <% end %>
    
    <div class="card-footer">
      <div class="collapse" id="provider_credentials_new_form">
        <%= render partial: "provider_templates/provider_credentials_new_form" %>
      </div>
    </div>  
    
  </ul>
</div>

app/views/provider_templates/_provider_credentials_new_form.html.erb
<form action="/create_provider_credential" method="post">

  <input type="hidden" name="provider_id" value="<%= @provider.id %>">

  <div class="form-group">
    <label for="credential_id">
      Credential
    </label>

    <%= select_tag(:credential_id, options_from_collection_for_select(Credential.all, :id, :name), :include_blank => 'Select a credential', :class => "form-control") %>
  </div>
  
  <button class="btn btn-block btn-outline-secondary">
    Add credential
  </button> 
</form>

app/views/provider_templates/_provider_encounters.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Encounters (<%=@provider.encounters.count%> total)

  </div>

  <ul class="list-group list-group-flush">
    <% @provider.encounters.each do |encounter| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/encounters/<%= encounter.id %>">
          <%= encounter.patient.firstname%> <%= encounter.patient.lastname%> seen on <%= encounter.created_at.to_date%> @ <%= encounter.location.name%>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/provider_templates/_provider_prescriptions.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Prescriptions (<%=@provider.prescriptions.count%> total)

  </div>

  <ul class="list-group list-group-flush">
    <% @provider.prescriptions.each do |prescription| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/prescriptions/<%= prescription.id %>">
          <%= prescription.medication.name_with_dosage %> for <%= prescription.patient.fullname %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/provider_templates/_provider_provider_credentials.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Provider Credentials

    <a data-toggle="collapse" href="#provider_provider_credentials_new_form">
      Add provider credential
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @provider.provider_credentials.each do |provider_credential| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/provider_credentials/<%= provider_credential.id %>">
          <%= provider_credential.provider_id %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/provider_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All providers
    </h1>

    <!--<a href="/providers/new" class="btn btn-block btn-outline-secondary">-->
    <!--  Add a new provider-->
    <!--</a>-->
  </div>
</div>





<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>

        <th>
          First name
        </th>

        <th>
          Last name
        </th>
        
        <th>
          Credentials
        </th>        

        <th>
          Email
        </th>

        <th>
        </th>
      </tr>

      <% @providers.each do |provider| %>
      <tr>

        <td>
          <%= provider.firstname %>
        </td>

        <td>
          <%= provider.lastname %>
        </td>
        
        <td>
          <% credentials = [] %>
          <% provider.credential_ids.each do |credential| %>
              <% credentials.push(Credential.find(credential).name) %>
          <% end %>
          <%= credentials.join(", ")%>
        </td>

        <td>
          <%= provider.email %>
        </td>

        <td>
          <a href="/providers/<%= provider.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="row mb-3">
      <div class="col-md-12">
        <%= paginate @providers, theme: "twitter-bootstrap-4" %>
      </div>
    </div>

  </div>
</div>

app/views/provider_templates/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <h1>
      Provider details for <%= @provider.fullname %>
    </h1>

    <div class="row mb-3">
      <div class="col">
        <a href="/providers" class="btn btn-block btn-outline-secondary">
          Go back
        </a>
      </div>

      <% if @provider.id == current_provider.id %>
        <div class="col">
          <a href="/providers/edit" class="btn btn-block btn-outline-secondary">
            Edit provider
          </a>
        </div>
      <% else %>
      <% end %>

    </div>

    <dl>
      <dt>
        First name
      </dt>
      <dd>
        <%= @provider.firstname %>
      </dd>

      <dt>
        Last name
      </dt>
      <dd>
        <%= @provider.lastname %>
      </dd>

      <dt>
        Email
      </dt>
      <dd>
        <%= @provider.email %>
      </dd>

    </dl>
  </div>
</div>

<% if @provider.credentials.count > 0 %>
  <div class="row mb-3">
    <div class="col-md-8 offset-md-2">
      <%= render partial: "provider_templates/provider_credentials" %>
    </div>
  </div>
<% else %>
<% end %>


<% if @provider.encounters.count > 0 %>
  <div class="row mb-3">
    <div class="col-md-8 offset-md-2">
      <%= render partial: "provider_templates/provider_encounters" %>
    </div>
  </div>
<% else %>
<% end %>

<% if @provider.prescriptions.count > 0 %>
  <div class="row mb-3">
    <div class="col-md-8 offset-md-2">
      <%= render partial: "provider_templates/provider_prescriptions" %>
    </div>
  </div>
<% else %>
<% end %>

<% if @provider.approved_encounters.count > 0 %>
  <div class="row mb-3">
    <div class="col-md-8 offset-md-2">
      <%= render partial: "provider_templates/provider_approved_encounters" %>
    </div>
  </div>
<% else %>
<% end %>